version: '3'
services:
  frontend:
    build: 
      context: ./frontend
    environment:
      - ENDPOINT=http://localhost:9000/api
      - NODE_ENV=dev
    ports:
     - "8000:8000"
    volumes:
      - ./frontend/src:/frontend/src 
  backend:
    build: 
      context: ./backend
    environment:
      - APPID=e557dda35ce7f17314b70fe4c595a9ae
      - NODE_ENV=dev
    ports:
      - "9000:9000" 
    volumes:
      - ./backend/src:/backend/src   